lyrgard/ffbeEquip

data.json
Spelling from Persistance to Persistence
Stats from +30% SPR to +20% SPR
=> Fixed spelling and stats for Persistence TMR

core.js, index.html
Cleaned using javascript now.
Live test runing at: http://oakz.org/ffbeEquip/
=> Clean HTML

data.json
As promised, here are the new items coming out after maintenance. Please if this PR needs rework or formatting, don't hesitate to let me know.
=> Adds the new items from Aigaion trial

static/units.css, static/units.js
My IDE also removed extra spaces in empty lines or at the end of lines, plus adding an extra line at the end of the file.
=> Add an indicator for limited time units

static/GL/monsters.json
Removes the ronsos and adds the new raid boss.
Please tell me if this works well, or if you need any changes.
=> Adds Garuda to the monster list

README.md, config.js, server.js, server/lib/firebase.js, server/routes/clientConfig.js, static/builder.html, static/builder.js, static/units.html, static/units.js
I removed the hardcoded links to buckets and placed them into config.json
I also added a route for client-side config that is included into builder.html and units.html that attaches configuration to the window object. It is then used for any client-side request.
=> Extracted firebase configuration into config.json

README.md, config.js, server.js, server/lib/firebase.js, server/routes/clientConfig.js, server/routes/firebase.js, static/builder.html, static/builder.js, static/units.html, static/units.js
Added slot information to builds, so they can be reproduced correctly.
=> For for Issue 102

README.md
Setting 127.0.0.1 is wrong, as it will mix up cookie headers for OAuth, I just fell into that trap :)
=> Change loopback IP to localhost domain instead

static/inventory.js, static/main.js, static/unitSearch.js, static/units.js
Hello,
Another QoL update, for the search box this time.
Simply press ESCAPE anywhere on the page to reset the searchbox.
This is something quite usual with search form.
Hope you like it.
=> Press Escape to reset search box

static/units.js
=> Export was iterating over wrong units

static/builder.js, static/units.js
This was reproducible by either:
1. Trying to pin an IW-enchanted item after it had been auto-selected in a build
or
2. Selecting an IW-enchanted item, then unpinning/pinning it
=> Issue 129 - Fixed pinning of enchanted items

static/units.js
Fix issue reported on Discord after introduction of image lazy loading.
=> Fix Units export as image function

static/builder.html, static/builderHelp.html, static/contribute.html, static/espers.html, static/index.html, static/inventory.html, static/units.html
Added link to this github in the footer.
I actually didn't know the code was accessible before manually searching on Google for ffbeEquip...
I think it may helps people to find the repo, and contribute / open issue.
=> Add github link on footer

static/units.css, static/units.html
Fix units page when there is no units (search for something not existing).
=> Fix units page

static/units.css, static/units.html, static/units.js
Various enhancements: 
- stats are displayed inside a table, therefor the positioning is always respected
- Unit export link is now visible in small screen, take some space above the tabs
- When searching, and there is no units to display, hide jump and show a message
=> QoL for units page

static/builder.html, static/common.css, static/common.js, static/contribute.html, static/espers.css, static/espers.html, static/espers.js, static/index.html, static/inventory.css, static/inventory.html, static/inventory.js, static/unitSearch.html, static/units.css, static/units.html, static/units.js
- Improved Inventory button for small screens (in the banner)
- Improved messages (uses alert bootstrap)
- Improved Espers page for small screens
=> Some improvement mainly for small screens

static/common.css
As identified by Acidion on Discord, fix a bug introduced by recent work on mobile.
=> Fix dropdown

static/espers.html
Esper page is missing reference to a CSS file.
=> Fix Esper page

static/espers.css, static/espers.js
Simple PR to be able to distinguish between owned/not owned espers.
=> Espers: distinguish tabs between owned/not owned

static/builder.js
=> Builder: open select when click on plus

static/builder.js, static/common.js, static/constants.js, static/index.html, static/main.js
For Encyclopedia to be similar with Unit Search page:
- Add magical/physical killers
- add tooltips
=> Encyclopedia: add magical/physical killers + tooltips

static/espers.js
=> Espers page: fix bug Share Link button not visible

static/builder.js
Maybe I got it right this time?
=> Corrected Build as Text

static/formula.js
Not sure if MP_TURN is an appropriate name..
=> Add stop and charm to custom formula. Also add abbreviation for MP/TURN.
