package-lock.json, package.json, server.js, server/lib/drive.js, server/lib/migration.js, server/lib/oauth.js, server/lib/shortener.js, server/middlewares/oauth.js, server/migrations/itemInventory/2_name_to_id.js, server/migrations/itemInventory/3_agrias_tmr.js, server/routes/drive.js, server/routes/oauth.js, test/server/middlewares/test.oauth.js, test/server/utils.js
Hi @lyrgard
Following on the previous PR, here is a refactoring of the gDrive routes.
I've added the necessary logic into the OAuth middleware to extend OAuth session time if possible by using the `refresh_token`.
Btw, do you still use `/:server/items/temp` route ?
=> refactor(server): drive routes and logic

static/builder.js
Fix for https://github.com/lyrgard/ffbeEquip/issues/103
I think there could be some rework in the amount of onUnitChange refreshes, and that the sixstarForm could actually be reflected in the unit data, instead of having to be marshalled. However, this is a super-fast fix that's not too hacky.
It introduces a sixstarForm variable to the unit in onUnitChange (line 768) that is later used to build the correct ID in loadBuild (which earlier just used raw unit.id which did not carry 6* form information)
=> Fix for issue 6* builds linking to 7* unit

static/builder.html, static/builder.js, static/common.css, static/common.js
One thing that bothered me a bit is the disconnection between common.js and builder.js. Specifically for displaying an item row. It's a bit awkward as now the excluded state has to be passed onto common.js, that should technically not have to know about it.
=> Added possibility to exclude items in search results

static/units.js
Added several title tag to help when managing units (example with Lightning):
- On the unit itself, added `Add one Lightning to your collection`
- In Edit mode, on the left plus, added `Add one Lightning to your collection`
- In Edit mode, on the left minus, added `Remove one Lightning from your collection`
- In Edit mode, on the right plus, added `Augment by one the number of TMR remaining`
- In Edit mode, on the right minus, added `Reduce by one the number of TMR remaining`
Tell me if the help text is not clear or anything 😺
=> Add help title for several actions on units page

static/units.js
Hello
This is my first attempts to implements #122
I noticed that the relevant function is already here (`toLink()`).
We just need to call it for the unit's name (and TMR's).
I couldn't test it locally as I didn't complete the OAUTH config yet...
I wish there would be a way to try the server without the state save feature...
I think it should be fine, except maybe for units with looong name, e.g.  `Atoning Dragoon Kain` or `Heavenly Technician Lid`...
=> Add wiki links for units and TMRs

.editorconfig
In the `.editorconfig` file, the indent size is set to 2.
I have nothing against it. However, most of the file are indented using 4 spaces...
Examples: `units.js` or `main.js`
=> Fix editor config tab size

static/units.css, static/units.js
Hello,
Here I am, with another little QoL change!
A rarity jump list is added at the beginning of the unit list.
I simply use anchor to jump to the rarity.
Here what it looks like:
Of course, it's flexible 😉
=> Units: add rarity jump list

static/common.js, static/inventory.css, static/inventory.js
Hello again!
To be more similar to units page, here is a PR to **present equipments by types**:
...
No name are shown, since there is, for now, no equivalent between internal type (e.g. `greatSword`) and full type name (e.g. `Great Sword`). Also it would have to be translated and all. So to keep it simple, only picture type is shown.
The async aspect was kept, but with types, the equipments are loaded by batch of same type (instead of batch of 20).
The materia listing is not modified, as the data currently doesn't allow us to discriminate between them (they all have `materia` as type). It would have been cool to sort by type as well (active, passive, etc...) like in game.
=> Inventory: show equipments by types

static/common.css, static/common.js, static/inventory.html, static/inventory.js, static/units.html, static/units.js
When showing the units page:
When showing the inventory page:
This is a crazy amount of request!
To greatly reduce the number of request made, and to improve performance in browser, this PR implements lazy loading of units and equipments image.
With lazy loading, units page:
With lazy loading, inventory page:
Of course, if the user scroll all the way down, all image will be loaded. But at least the first display will not overload the browser. This is especially true for mobile users.
The great library [lazyload](https://github.com/verlok/lazyload) is used to implement this.
=> Performance: lazyloading of units/equipments image

static/builder.html, static/builderHelp.html, static/common.js, static/contribute.html, static/espers.html, static/espers.js, static/index.html, static/inventory.html, static/unitSearch.html, static/units.html
Security improvement again (#124).
When using `target="_blank"` in link, the parent page (on FFBEequip) could be modified by the target page (ex: wiki gamepedia) by using the `window.opener.location` object.
More information: https://mathiasbynens.github.io/rel-noopener
To avoid this issue, we need to define `rel="noreferrer"` for all external links using blank target.
=> Add noreferrer for external link with _blank

static/units.css, static/units.html, static/units.js
Indigo here again with a nice PR to improve the Units page for small screen!
Here how the **actual** page looks on various screen size:
---
Here how the **new** page looks on various screen size:
---
Modified: 
- The left sidebar (with stats and simple/edit mode toggle) can be collapsed to gain space
- The sidebar is no longer visible on tablet and mobile. The stats are moved at the top (collapsable) and the simple/edit mode toggle is fixed on the bottom right corner.
- The "share unit collection" looks more like a button, has its text removed on tablet and is not visible on mobile
=> Rework Units page for small screen

static/inventory.css, static/inventory.html, static/inventory.js, static/units.css, static/units.js
After the Units page, the Inventory page!
Lots of improvements for small screen, and as a bonus add some stats (just like units).
**Screenshot of large screen:**
**Screenshot of small screen:**
Added: little improvements for Units page to autocollapse the stats when the screen is small (at loading time only).
=> Rework inventory for small screen

static/inventory.css, static/inventory.js
The idea here is to avoid adding the jumps one by one, which leads to the height moving.
The jump are all added, then we enable them one by one.
=> Inventory jump list: avoid loading jump one by one

static/espers.css, static/espers.html, static/espers.js
Reworked Espers page for small screen.
Wow, this one was tricky.
1. For small screen, the stats and the board are separated in two views. You can switch between the views with the toggle button on the bottom right.
2. The Esper selector at the top is now forced to a single line (to gain space)
3. The link dialog now adapt to small screen
4. A fixed label with the current SP counter is displayed at the bottom right if the first one is not visible
**Before:**
**After (stats view)**
**After (board view)**
=> Rework Espers page for small screen

package-lock.json, package.json, server.js, server/routes/clientConfig.js, static/builder.html, static/builderHelp.html, static/contribute.html, static/espers.html, static/index.html, static/inventory.html, static/unitSearch.html, static/units.html
As discussed in #124 
Implements the following security headers (see doc https://helmetjs.github.io/) : 
- dnsPrefetchControl
- frameguard
- ieNoOpen
- noSniff
- referrerPolicy
- xssFilter
- contentSecurityPolicy
For the last one, as this is the trickiest one, it is actually set to `report only` in the code, in production.
Hence, in production, any rule violation will not trigger a block, and only report to the reporting URI set.
After some time, when we are confident that the CSP do not block any useful content, we will move to `enforce` option.
**Before merging**, you will need to go to https://report-uri.com, create an account, create the subdomain `ffbeequip` in order to obtain the reporting address `https://ffbeequip.report-uri.com/r/d/csp/reportOnly`.
**After merging**, you will …
=> Add security headers with helmetjs

static/espers.css, static/espers.js
After discussion with @lyrgard, made some enhancement to avoid getting the toggle button on desktop.
On mobile, when toggling, the espers selector bar is now hidden as well, so we have even more space to display the grid!
=> Enhance Espers page (again)

static/inventory.js
Fix a bug introduced by lazyloading.
When opening item management popup, image was not loading:
Fixed:
=> Fix lazyload bug in inventory (item enhancement)

static/builder.html, static/builderHelp.html, static/checkWebWorker.html, static/contribute.html, static/espers.html, static/index.html, static/inventory.html, static/unitSearch.html, static/units.html
As the title suggests...
HTML documents requires a doctype, as per the W3C spec.
=> Add HTML5 doctype

static/builder.js
Ok, this one is smallest to date!
Fixes #104 " Persistent goal marker over multiple units"
The jQuery selector was targeting only div right below the results stats, hence missing the resists divs.
We simply select all element with `statToMaximize` to remove it... 😸  Nice and easy!
=> Fix Persistent goal marker not being reset for resists stats

static/common.css, static/units.html, static/units.js
After quite some feedbacks, it seems a lot of people are having issue with Simple/Edit mode.
This little PR aims to offer a little guidance for newcomers, by displaying a message in the Units page when there are no units in the collection.
=> Add help message for Units page for Simple/Edit Mode

static/builder.css, static/common.css
As asked by @Darwe (Canine) on Discord:
> Small feature request - when a build is calculating, can the Unit Info link still be available? It might also be good to allow the reddit/discord/github/etc links to be available, so people can easily come ask questions or chat while long builds are running
=> Show more links while building

package-lock.json, package.json, server.js, tools/ansible/templates/apache2/vhost.alias.conf.j2, tools/ansible/templates/apache2/vhost.server.conf.j2, webpack.config.js
This PR build on the amazing work of @Adezandee (tagging for review)
1. Set cache-related headers for static file serving:
- `ETag` is disabled (in favor of `Last-Modified` and `Cache-Control`)
- `Last-Modified` and `Cache-Control` activated in production
- `Cache-Control` set with huge Max-Age (1 year) for files in `dist` (+ immutable)
- `Cache-Control` set to zero for HTML files in `dist`
- `Cache-Control` set to one hour for files in `static`
2. Minify JS using babel-loader
3. Clean `dist` folder before building
4. CSP: don't report in dev
I added the command `start:useDist` to be able to test serving from `dist` even in development (since in production, HTTPS is mandatory and dev server doesn't have TLS enabled usually).
=> Performance: enable Cache headers and JS minify

static/builder.js
- Hide previous modal after button is clicked
Reference Issue: #235
=> Fix "Reset item exclusion list" creating infinite modals

static/common.css, static/inventory.css, static/units.css
Fix #240 once and for all.
Note that I reverted your commit on the zindex of the buttons.
Issue was regarding the stacking context root: `#header` had a z-index of only one. Simply setting it to 99 (below glass panel) is enough to work everywhere.
=> Fix overlay menu issue

static/GL/releasedUnits.json
As mentioned in issue #366, IF Katy is not currently flagged as time-limited; updated `releasedUnits.json` to correct
=> updating Immortal Flame Katy as time-limited
